apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  - image: busybox
    name: busybox
    command: ["/bin/sh", "-c"] # start a shell in non-interactive mode
    args: ["sleep 1000"] # sleep for 1000s
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  volumes:
  - name: scratch-volume
    emptyDir:
      sizeLimit: 500Mi
