apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: "{}"
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      envFrom:
        - configMapRef:
            name: app-config
