apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: "{}"
spec:
  containers:
    - image: busybox
      name: test-pod
      resources:
        requests:
          cpu: "10m"
          memory: "4Mi"
        limits:
          cpu: "20m"
          memory: "8Mi"
      command: ["sleep", "infinity"]
      envFrom:
        - configMapRef:
            name: app-config
