apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: "{}"
spec:
  containers:
    - image: nginx
      name: nginx
      env:
        - name: SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SERVICE_ENDPOINT
