apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: "{}"
spec:
  containers:
    - image: busybox
      name: test-pod
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      command: ["sleep", "infinity"]
